# Generated by Django 3.1.6 on 2021-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
