# Generated by Django 3.1.6 on 2021-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
    ]
